version: '3.8'

services:
  n8n:
    build: .
    container_name: n8n-v2

    restart: always
    ports:
      - "5678:5678"
    environment:
      - TZ=Europe/Madrid   
      - GENERIC_TIMEZONE=Europe/Madrid
      - DB_TYPE=sqlite
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_WORKFLOWS_FOLDER=/home/node/workflows

    volumes:
      - ./data/.n8n:/home/node/.n8n  # ✅ Your local 
      - ./workflows:/home/node/workflows # ✅ workflow default folder